image: jakzal/phpqa:php7.4

before_script:
  - composer install

cache:
  paths:
    - vendor/

stages:
  - securityChecker
  - CodingStandards
  - UnitTests

security-checker:
  stage: securityChecker
  script:
    - local-php-security-checker  --path=./composer.lock
  allow_failure: false

phpcs:
  stage: CodingStandards
  script:
    - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src ./tests
  allow_failure: false

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: false

#phpunit:
#  stage: UnitTests
#  script:
#    - php bin/console --env=test doctrine:database:create
#    - php bin/console --env=test doctrine:schema:create
#    - php bin/console --no-interaction --env=test doctrine:fixtures:load
#    - php bin/phpunit
#  allow_failure: false
#
#services:
#  - mariadb:latest
#
#variables:
#  MYSQL_DATABASE: P8_SF53
#  MYSQL_ROOT_PASSWORD: admin
