#image: tokashi69/mytest
image: jakzal/phpqa:php5.5

before_script:
  - composer install

cache:
  paths:
    - vendor/

stages:
  - securityChecker
  - CodingStandards
  - UnitTests

security-checker:
  stage: securityChecker
  script:
    - local-php-security-checker  --path=./composer.lock
  allow_failure: true

phpcs:
  stage: CodingStandards
  script:
    - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
  allow_failure: true

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: true

phpunit:
  stage: UnitTests
  script:
    - composer require --dev dbrekelmans/bdi && vendor/bin/bdi detect drivers
    - php bin/phpunit
  allow_failure: true

phpmd:
  stage: CodingStandards
  script:
    - phpmd src text cleancode,codesize,controversial,design,naming,unusedcode
  allow_failure: true