version: "3.8"
services:
  webapp_p8_sf53_apache_profiler:
    build: .
    container_name: P8_TODO_SF53_APACHE_PROFILER
    ports:
      - '4080:80'
      - '4081:443'
    volumes:
      - ../:/var/www/html/
    command: sleep infinity

networks:
  default:
    external:
      name: my-network