version: "3.8"
services:
  webapp_p8_sf53_apache:
    build: .
    container_name: P8_TODO_SF53_APACHE
    ports:
      - '4070:80'
      - '4071:443'
    volumes:
      - ../:/var/www/html/
    command: sleep infinity

networks:
  default:
    external:
      name: my-network