version: "3.8"
services:
  webapp_p8:
    build: .
    container_name: P8_TODO
    ports:
      - '4050:8000'
    volumes:
      - ../:/workspaces/p8/
    command: sleep infinity

networks:
  default:
    external:
      name: my-network