version: "3.8"
services:
  webapp_p8_blackfire:
    build: .
    container_name: P8_TODO_BLACKFIRE
    ports:
      - '4055:8000'
    volumes:
      - ../:/workspaces/p8/
    command: sleep infinity

networks:
  default:
    external:
      name: my-network